apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp4-net-observ
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/lpanza/ocp4-network-observability.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
