apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators-redhat

resources:
- operatorgroup.yaml
- subscription.yaml
- namespace.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "30"
