apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: netobserv

commonAnnotations:
  argocd.argoproj.io/sync-wave: "35"

resources:
- clusterrole.yaml
- loki-stack.yaml
- clusterrolebinding.yaml
