apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: netobserv
spec:
  managementState: Managed
  logStore:
    type: lokistack
    lokistack:
      name: lokistack-sample
  collection:
    type: vector
