apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- clusterlogging.yaml
- subscription.yaml
- namespace.yaml
- clusterlogging.yaml

commonAnnotations:
  argocd.argoproj.io/sync-wave: "50"
