apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: lokistack-sample
  namespace: netobserv
spec:
  tenants:
    mode: openshift-logging
  managementState: Managed
  limits:
    global:
      queries:
        queryTimeout: 1m
  storage:
    schemas:
      - effectiveDate: '2022-06-01'
        version: v12
    secret:
      name: loki-netobserv-claim
      type: s3
  hashRing:
    type: memberlist
  size: 1x.small
  storageClassName: gp2
